name:                lenses-intro
version:             0.1.0.0
github:              "dktn/lenses-intro"
license:             BSD3
author:              "Adam Szlachta"
maintainer:          "adam.szlachta@gmail.com"
copyright:           "2019 Adam Szlachta"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dktn/lenses-intro#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- lens

library:
  source-dirs: src

executables:
  lenses-intro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lenses-intro

tests:
  lenses-intro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lenses-intro
